name: SENGC
channels:
  - pytorch
  - defaults
  - conda-forge
  - bioconda
dependencies:
  - _libgcc_mutex=0.1
  - _pytorch_select=0.1
  - blas=1.0
  - ca-certificates=2020.6.24
  - certifi=2020.6.20
  - cffi=1.14.0
  - cudatoolkit=10.1.243
  - cudnn=7.6.5
  - cvxpy=1.1.7
  - cvxpy-base=1.1.7
  - cycler=0.10.0
  - dbus=1.13.16
  - ecos=2.0.7.post1
  - expat=2.2.9
  - fontconfig=2.13.0
  - freetype=2.10.2
  - future=0.18.2
  - glib=2.65.0
  - gst-plugins-base=1.14.0
  - gstreamer=1.14.0
  - icu=58.2
  - intel-openmp=2019.4
  - joblib=0.15.1
  - jpeg=9b
  - kiwisolver=1.2.0
  - lcms2=2.11
  - ld_impl_linux-64=2.33.1
  - libedit=3.1.20191231
  - libffi=3.3
  - libgcc-ng=9.1.0
  - libgfortran-ng=7.3.0
  - libpng=1.6.37
  - libstdcxx-ng=9.1.0
  - libtiff=4.1.0
  - libuuid=1.0.3
  - libxcb=1.14
  - libxml2=2.9.10
  - lz4-c=1.9.2
  - matplotlib=3.2.1
  - matplotlib-base=3.2.1
  - mkl=2019.4
  - mkl-service=2.3.0
  - mkl_fft=1.1.0
  - mkl_random=1.0.4
  - ncurses=6.2
  - ninja=1.9.0
  - numpy=1.18.5
  - numpy-base=1.18.5
  - olefile=0.46
  - openblas=0.3.3
  - openssl=1.1.1g
  - osqp=0.6.1
  - pandas=1.0.5
  - patsy=0.5.1
  - pcre=8.44
  - pillow=7.2.0
  - pip=20.1.1
  - pycparser=2.20
  - pyparsing=2.4.7
  - pyqt=5.9.2
  - python=3.7.7
  - python-dateutil=2.8.1
  - python_abi=3.7
  - pytorch=1.6.0
  - pytz=2020.1
  - qt=5.9.7
  - readline=8.0
  - scikit-learn=0.22.1
  - scipy=1.5.0
  - scs=2.0.2
  - seaborn=0.11.0
  - setuptools=47.3.1
  - sip=4.19.8
  - six=1.15.0
  - sqlite=3.32.3
  - statsmodels=0.11.1
  - tk=8.6.10
  - torchvision=0.7.0
  - tornado=6.0.4
  - wheel=0.34.2
  - xz=5.2.5
  - zlib=1.2.11
  - zstd=1.4.5
